version: "3.7"
services:
  python-stock:
    container_name: python-stock
    build:
      context: ./
      dockerfile: Dockerfile
    working_dir: "/opt/app/src"
    ports:
      - "9000:9000"
    networks:
      - stock-network
    logging:
      options:
        max-size: 10m
        max-file: "10"
    expose:
      - 9000

networks:
  stock-network:
