version: "3.7"
services:
  python-stock:
    container_name: python-stock
    build:
      context: ./
      dockerfile: Dockerfile
    working_dir: "/opt/app/src"
    volumes:
      - ./src/main.py:/opt/app/src/main.py
    networks:
      - stock-network
    logging:
      options:
        max-size: 10m
        max-file: "10"

networks:
  stock-network:
